apiVersion: v1
kind: Service
metadata:
  name: jdownloader-svc
  labels:
    app: jdownloader
spec:
  ports:
  - name: http
    port: 5800
    protocol: TCP
    targetPort: 5800
  selector:
    app: jdownloader
